### ISSUE TITLE
Run Project with DevContainer

### ISSUE THREAD

**Issue by walid-sadaoui** [Magizchi/pdf-man-from-sveltekit#1]
Le .devcontainer.json contient une commande postCreateCommand qui lance le serveur de dev mais il manque l'installation des dépendances, ce qui provoque une erreur :
sh: 1: vite: not found
[206748 ms] postCreateCommand failed with exit code 127. Skipping any further user-provided commands.

Il faudrait mettre à jour la config du devcontainer pour lancer tous les services nécessaire présents dans le docker-compose.yml. Il faut utiliser une image qui contient une installation de Docker.

**Comment by Magizchi** [comment]
Ha oui

Corriger en ajoutant "npm install" du coup
